name: CI/CD Pipeline for Model Development

# Trigger the workflow on push or pull request to the main branch
on:
  push:
    branches:
      - hashwanth_model_pipeline
  pull_request:
    branches:
      - main

jobs:
  # Job to set up the environment and run tests and model development
  build-and-develop:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the code from the repository
    - name: Checkout code
      uses: actions/checkout@v2

    # Step 2: Set up Python environment
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  # Specify your Python version

    # Step 3: Install dependencies from requirements.txt
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Step 4: Run unit tests (if you have a 'tests' folder)
    - name: Run unit tests
      run: |
        python -m unittest discover tests

    # Step 5: Run model development script using MLflow
    - name: Run Model Development with MLflow
      run: |
        python src/Model_Pipeline/model_development_with_mlflow.py