name: Deploy to GCP

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch
      - vignesh_dev_check_1  # Additional branch for testing

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v0
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name: Build Docker image
      run: |
        docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/bank-marketing-prediction:${{ github.sha }} .

    - name: Push Docker image to Artifact Registry
      run: |
          docker tag gcr.io/${{ secrets.GCP_PROJECT_ID }}/bank-marketing-prediction:${{ github.sha }} \
            us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/bank-marketing-prediction-artifact-repo/bank-marketing-prediction:${{ github.sha }}
          docker push us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/bank-marketing-prediction-artifact-repo/bank-marketing-prediction:${{ github.sha }}

    - name: Create new instance template
      run: |
        gcloud compute instance-templates create bank-marketing-prediction-template-${{ github.sha }} \
          --machine-type=e2-micro \
          --image=us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/bank-marketing-prediction-artifact-repo/bank-marketing-prediction:${{ github.sha }} \
          --network=bank-marketing-prediction-mlops-vpc \
          --subnet=bank-marketing-prediction-mlops-vpc-subnet \
          --metadata-from-file=startup-script=startup-script.sh

    - name: Update managed instance group
      run: |
        gcloud compute instance-groups managed rolling-action start-update bank-marketing-mig \
          --version=template=bank-marketing-prediction-mlops-template-${{ github.sha }} \
          --max-surge=1 \
          --max-unavailable=0 \
          --zone=us-central1  # Change to your zone if different