name: Deploy to GCP

on:
  push:
    branches:
      - main
      - vignesh_dev_check_1

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}

    - name: Authenticate Docker
      run: |
        gcloud auth configure-docker us-central1-docker.pkg.dev

    - name: Build Docker image
      run: |
        docker build -t us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/bank-marketing-prediction-artifact-repo/bank-marketing-prediction:${{ github.sha }} .

    - name: Push Docker image to Artifact Registry
      run: |
        docker push us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/bank-marketing-prediction-artifact-repo/bank-marketing-prediction:${{ github.sha }}

    - name: Create new instance template
      run: |
        gcloud compute instance-templates create bank-marketing-prediction-template \
          --machine-type=e2-micro \
          --image=us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/bank-marketing-prediction-artifact-repo/bank-marketing-prediction:${{ github.sha }} \
          --network=bank-marketing-prediction-mlops-vpc \
          --subnet=bank-marketing-prediction-mlops-vpc-subnet \
          --region=us-central1 \
          --metadata-from-file=startup-script=gcpdeploy/startup-script.sh
            
    - name: Update managed instance group
      run: |
        gcloud compute instance-groups managed rolling-action start-update bank-marketing-mig \
          --version=template=bank-marketing-prediction-template-${{ github.sha }} \
          --max-surge=1 \
          --max-unavailable=0 \
          --zone=us-central1-c