name: Model Pipeline CI/CD

on:
  push:
    branches:
      - hashwanth_model_cicd  # or your specific branch
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  run_model_pipeline:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'  # Specify your Python version

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Ensure you have a requirements.txt file in your repo

      # Step 4: Run model training and evaluation script
      - name: Run model development and evaluation
        run: |
          python src/Model_Pipeline/model_dev.py  # Path to your model development script

      # Optional Step 5: Run model comparison script (if applicable)
      - name: Compare best models
        run: |
          python src/Model_Pipeline/compare_best.py  # Path to your model comparison script

      # Optional Step 6: Push model to GCP (if applicable)
      - name: Push best model to GCP
        run: |
          python src/Model_Pipeline/push.py  # Path to your GCP upload script
