name: GCP Deploy CI/CD

on:
  push:
    branches:
      - Sheela-deployment  # Test 4

env:
  PROJECT_ID: iconic-vine-438222-u6
  ZONE: us-central1-a
  SETUP_SCRIPT_PATH: gcpdeploy/setup-CI_CD.sh
  
jobs:
  create-vm-instance:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ env.PROJECT_ID }}
          install_components: gcloud

      - name: Create VPC
        run: |
          gcloud compute networks create term-deposit-prediction-vpc \
            --project=${{ env.PROJECT_ID }} \
            --subnet-mode=custom

      - name: Create Subnet
        run: |
          gcloud compute networks subnets create term-deposit-prediction-subnet \
            --project=${{ env.PROJECT_ID }} \
            --network=term-deposit-prediction-vpc \
            --region=us-central1 \
            --range=10.0.0.0/24

      - name: Create Firewall Rules
        run: |
          # Allow SSH
          gcloud compute firewall-rules create allow-ssh \
            --project=${{ env.PROJECT_ID }} \
            --network=term-deposit-prediction-vpc \
            --allow=tcp:22

          # Allow HTTP
          gcloud compute firewall-rules create allow-http \
            --project=${{ env.PROJECT_ID }} \
            --network=term-deposit-prediction-vpc \
            --allow=tcp:80

          # Allow TCP connections on port 20
          gcloud compute firewall-rules create allow-tcp-20 \
            --project=${{ env.PROJECT_ID }} \
            --network=term-deposit-prediction-vpc \
            --allow=tcp:20

          # Allow TCP connections on port 8000
          gcloud compute firewall-rules create allow-tcp-8000 \
            --project=${{ env.PROJECT_ID }} \
            --network=term-deposit-prediction-vpc \
            --allow=tcp:8000


      - name: Create VM
        run: |
          gcloud compute instances create term-deposit-prediction-instance \
            --zone=${{ env.ZONE }} \
            --machine-type=e2-micro \
            --subnet=term-deposit-prediction-subnet

      - name: Copy Setup Script to VM
        run: |
          echo "Copying setup script to VM..."
          gcloud compute scp ./${{ env.SETUP_SCRIPT_PATH }} term-deposit-prediction-instance:/home/${USER}/setup-CI_CD.sh --zone=${{ env.ZONE }}

      - name: Run Setup Script on VM
        run: |
          echo "Running setup script on VM..."
          gcloud compute ssh term-deposit-prediction-instance --zone=${{ env.ZONE }} --command="chmod +x /home/${USER}/setup-CI_CD.sh && sudo sh /home/${USER}/setup-CI_CD.sh"
