name: GCP Deploy CI/CD

on:
  push:
    branches:
      - Sheela-deployment  # Test 1

env:
  PROJECT_ID: iconic-vine-438222-u6
  ZONE: us-central1-a
  SETUP_SCRIPT_PATH: gcpdeploy/setup-CI_CD.sh
  SUBNET_NAME: bank-marketing-prediction-mlops-vpc-subnet

jobs:
  create-vm-instance:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ env.PROJECT_ID }}
          install_components: gcloud

      - name: Create VM
        run: |
          gcloud compute instances create term-deposit-prediction-instance \
            --zone=${{ env.ZONE }} \
            --machine-type=e2-micro \
            --subnet=${{ env.SUBNET_NAME }} \
            --metadata-from-file startup-script=${{ env.SETUP_SCRIPT_PATH }}

      - name: Validate File Paths
        run: |
          echo "Validating script paths..."
          ls -lh ./${{ env.STARTUP_SCRIPT_PATH }}

      - name: Run Setup Script
        run: |
          gcloud compute ssh term-deposit-prediction-instance --zone=${{ env.ZONE }} --command="sudo sh /home/bank-marketing-prediction-mlops/Bank_Marketing_Prediction_MLops/gcpdeploy/setup-CI_CD.sh"
