name: Create VM Image

on:
  push:
    branches:
      - Sheela-deployment  # Trigger the workflow on push to the main branch

env:
  PROJECT_ID: iconic-vine-438222-u6
  IMAGE_NAME: bank-marketing-mlops-image
  IMAGE_FAMILY: bank-marketing-mlops-family
  IMAGE_DESCRIPTION: "Image for Bank Marketing MLOps App"
  INSTANCE_TEMPLATE_NAME: bank-marketing-template
  ZONE: us-central1-a
  SOURCE_INSTANCE: bank-marketing-prediction-mlops-instance
  STARTUP_SCRIPT_PATH: startup-script.sh
  SETUP_SCRIPT_PATH: setup.sh

jobs:
  create-vm-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ env.PROJECT_ID }}
          install_components: gcloud

      - name: Copy Startup and Setup Scripts to Instance
        run: |
          echo "Copying startup and setup scripts to the VM..."
          gcloud compute scp ./${{ env.SETUP_SCRIPT_PATH }} ${{ env.SOURCE_INSTANCE }}:/home/ --zone=${{ env.ZONE }}
          gcloud compute scp ./${{ env.STARTUP_SCRIPT_PATH }} ${{ env.SOURCE_INSTANCE }}:/home/ --zone=${{ env.ZONE }}

      - name: Run Setup Script on Instance
        run: |
          echo "Running setup script on the source instance..."
          gcloud compute ssh ${{ env.SOURCE_INSTANCE }} --zone=${{ env.ZONE }} --command="bash /home/${{ env.SETUP_SCRIPT_PATH }}"

      - name: Stop VM for Image Creation
        run: |
          echo "Stopping the source VM to create an image..."
          gcloud compute instances stop ${{ env.SOURCE_INSTANCE }} --zone=${{ env.ZONE }}

      - name: Create VM Image
        run: |
          echo "Creating a new VM image..."
          gcloud compute images create ${{ env.IMAGE_NAME }} \
            --source-disk=${{ env.SOURCE_INSTANCE }} \
            --source-disk-zone=${{ env.ZONE }} \
            --family=${{ env.IMAGE_FAMILY }} \
            --description="${{ env.IMAGE_DESCRIPTION }}" \
            --force

      - name: Start VM after Image Creation
        run: |
          echo "Starting the source VM after image creation..."
          gcloud compute instances start ${{ env.SOURCE_INSTANCE }} --zone=${{ env.ZONE }}
