name: Bank Marketing MLOps CI/CD

on:
  push:
    branches:
      - Sheela-deployment  # Test 1

env:
  PROJECT_ID: iconic-vine-438222-u6
  VM_INSTANCE: bank-marketing-prediction-mlops-instance
  ZONE: us-central1-a
  GCS_MODEL_PATH: gs://mlopsprojectdatabucketgrp6/models/best_random_forest_model/model.pkl
  LOCAL_MODEL_PATH: /home/bank-marketing-prediction-mlops/MLmodel.pkl

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ env.PROJECT_ID }}
          install_components: gcloud

      - name: Check VM status and start if stopped
        run: |
          VM_STATUS=$(gcloud compute instances describe ${{ env.VM_INSTANCE }} --zone=${{ env.ZONE }} --format="value(status)")
          if [ "$VM_STATUS" = "TERMINATED" ]; then
            echo "Starting VM instance..."
            gcloud compute instances start ${{ env.VM_INSTANCE }} --zone=${{ env.ZONE }}
            echo "Waiting for VM to be ready..."
            sleep 60
          else
            echo "VM instance is already running."
          fi

      - name: Deploy Model and Restart Service
        run: |
          echo "Connecting to VM to deploy model and restart service..."
          gcloud compute ssh ${{ env.VM_INSTANCE }} --zone=${{ env.ZONE }} --command="
            set -e  # Exit immediately if any command fails

            echo 'Ensuring the target directory exists...'
            sudo mkdir -p /home/bank-marketing-prediction-mlops
            sudo chown -R $USER:$USER /home/bank-marketing-prediction-mlops
            sudo chmod -R 755 /home/bank-marketing-prediction-mlops

            echo 'Checking if the GCS model exists...'
            export GCS_MODEL_PATH='${{ env.GCS_MODEL_PATH }}'
            export LOCAL_MODEL_PATH='${{ env.LOCAL_MODEL_PATH }}'

            gsutil ls \$GCS_MODEL_PATH || { echo 'Model not found in GCS. Exiting.'; exit 1; }

            echo 'Pulling model from GCS...'
            gsutil cp \$GCS_MODEL_PATH \$LOCAL_MODEL_PATH || { echo 'Failed to copy model. Exiting.'; exit 1; }

            echo 'Verifying model copy...'
            ls -lh \$LOCAL_MODEL_PATH || { echo 'Model not found in destination. Exiting.'; exit 1; }

            echo 'Restarting application service...'
            sudo systemctl restart bank-marketing-prediction.service || { echo 'Failed to restart service. Exiting.'; exit 1; }

            echo 'Deployment completed successfully.'
          "

      - name: Debugging Step (Optional)
        run: |
          gcloud compute ssh ${{ env.VM_INSTANCE }} --zone=${{ env.ZONE }} --command="
            echo 'Checking permissions of target directory...'
            ls -ld /home/bank-marketing-prediction-mlops

            echo 'Listing files in the target directory...'
            ls -lh /home/bank-marketing-prediction-mlops
          "
