name: Create VM Image

on:
  push:
    branches:
      - Sheela-deployment  # Trigger the workflow on push to the specified branch

env:
  PROJECT_ID: iconic-vine-438222-u6
  IMAGE_NAME: bank-marketing-mlops-image
  IMAGE_FAMILY: bank-marketing-mlops-family
  IMAGE_DESCRIPTION: "Image for Bank Marketing MLOps App"
  INSTANCE_TEMPLATE_NAME: bank-marketing-template
  ZONE: us-central1-a
  SOURCE_INSTANCE: bank-marketing-prediction-mlops-instance
  STARTUP_SCRIPT_PATH: gcpdeploy/startup-script.sh
  SETUP_SCRIPT_PATH: gcpdeploy/setup.sh

jobs:
  create-vm-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Validate File Paths
        run: |
          echo "Validating script paths..."
          ls -lh ./${{ env.STARTUP_SCRIPT_PATH }}
          ls -lh ./${{ env.SETUP_SCRIPT_PATH }}

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ env.PROJECT_ID }}
          install_components: gcloud

      - name: Prepare Target Directory on VM
        run: |
          echo "Preparing target directory on VM..."
          gcloud compute ssh ${{ env.SOURCE_INSTANCE }} --zone=${{ env.ZONE }} --command="
            sudo mkdir -p /home/$USER/ &&
            sudo chmod -R 755 /home/$USER/
          "

      - name: Copy Startup and Setup Scripts to Instance
        run: |
          echo "Extracting file names..."
          SETUP_SCRIPT_FILE=$(basename "${{ env.SETUP_SCRIPT_PATH }}")
          STARTUP_SCRIPT_FILE=$(basename "${{ env.STARTUP_SCRIPT_PATH }}")

          echo "Copying setup.sh..."
          gcloud compute scp ./${{ env.SETUP_SCRIPT_PATH }} ${{ env.SOURCE_INSTANCE }}:/home/$USER/$SETUP_SCRIPT_FILE --zone=${{ env.ZONE }} || { echo "Failed to copy setup.sh. Exiting."; exit 1; }

          echo "Copying startup-script.sh..."
          gcloud compute scp ./${{ env.STARTUP_SCRIPT_PATH }} ${{ env.SOURCE_INSTANCE }}:/home/$USER/$STARTUP_SCRIPT_FILE --zone=${{ env.ZONE }} || { echo "Failed to copy startup-script.sh. Exiting."; exit 1; }

      - name: Validate Script Paths on VM
        run: |
          SETUP_SCRIPT_FILE=$(basename "${{ env.SETUP_SCRIPT_PATH }}")
          STARTUP_SCRIPT_FILE=$(basename "${{ env.STARTUP_SCRIPT_PATH }}")

          gcloud compute ssh ${{ env.SOURCE_INSTANCE }} --zone=${{ env.ZONE }} --command="ls -lh /home/$USER/$SETUP_SCRIPT_FILE && ls -lh /home/$USER/$STARTUP_SCRIPT_FILE"
