name: Bank Marketing MLOps CI/CD

on:
  push:
    branches:
      - Sheela-deployment  #test5

env:
  PROJECT_ID: iconic-vine-438222-u6
  VM_INSTANCE: bank-marketing-prediction-mlops-instance
  ZONE: us-central1-a
  GCS_MODEL_PATH: gs://mlopsprojectdatabucketgrp6/models/best_random_forest_model/model.pkl
  LOCAL_MODEL_PATH: /home/bank-marketing-prediction-mlops/MLmodel

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ env.PROJECT_ID }}
          install_components: gcloud

      - name: Check VM status and start if stopped
        run: |
          VM_STATUS=$(gcloud compute instances describe ${{ env.VM_INSTANCE }} --zone=${{ env.ZONE }} --format="value(status)")
          if [ "$VM_STATUS" = "TERMINATED" ]; then
            echo "Starting VM instance..."
            gcloud compute instances start ${{ env.VM_INSTANCE }} --zone=${{ env.ZONE }}
            echo "Waiting for VM to be ready..."
            sleep 60  # Wait for 60 seconds to ensure the VM is fully started
          else
            echo "VM instance is already running."
          fi

      - name: Deploy Model from GCS and Restart Service
        run: |
          echo "Ensuring the target directory exists..."
          gcloud compute ssh ${{ env.VM_INSTANCE }} --zone=${{ env.ZONE }} --command=" \
          sudo mkdir -p /home/bank-marketing-prediction-mlops && \
          sudo chmod 755 /home/bank-marketing-prediction-mlops && \
          echo 'Directory prepared successfully.'; \
          "

          echo "Checking if the GCS model exists..."
          gcloud compute ssh ${{ env.VM_INSTANCE }} --zone=${{ env.ZONE }} --command=" \
          gsutil ls ${GCS_MODEL_PATH} || { echo 'Model not found in GCS. Exiting.'; exit 1; }; \
          "

          echo "Pulling model from GCS..."
          gcloud compute ssh ${{ env.VM_INSTANCE }} --zone=${{ env.ZONE }} --command=" \
          gsutil cp ${GCS_MODEL_PATH} ${LOCAL_MODEL_PATH} || { echo 'Failed to copy model. Exiting.'; exit 1; }; \
          "

          echo "Verifying model copy..."
          gcloud compute ssh ${{ env.VM_INSTANCE }} --zone=${{ env.ZONE }} --command=" \
          ls -lh ${LOCAL_MODEL_PATH} || { echo 'Model not found in destination. Exiting.'; exit 1; }; \
          "

          echo "Restarting application service..."
          gcloud compute ssh ${{ env.VM_INSTANCE }} --zone=${{ env.ZONE }} --command=" \
          sudo systemctl restart bank-marketing-prediction.service || { echo 'Failed to restart service. Exiting.'; exit 1; }; \
          "


