name: Trigger Airflow DAG

on:
  push:
    branches:
      - vignesh_model_dev_3  # Replace with your target branch

jobs:
  trigger-dag:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Install Docker Compose
      run: |
        sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2
      
    - name: Run Airflow and trigger DAG
      run: |
        docker compose up -d
        sleep 30  # Wait for Airflow to initialize
        docker exec airflow-webserver airflow dags trigger ModelDevelopmentPipeline
        docker compose down