name: Trigger Model Development Pipeline DAG

on:
  push:
    branches:
      - 'vignesh_cicd_check'  # Replace with the actual branch name you want to monitor

jobs:
  trigger_dag:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Build and run Airflow with Docker
      run: |
        # Start the Docker containers for Airflow
        docker compose -f docker-compose.yaml up -d
        
        # Wait for Airflow to be ready (you may need to adjust this based on your setup)
        sleep 30
        
        # Trigger the DAG locally
        docker-compose exec airflow-webserver airflow dags trigger modeldevelopmentpipeline  # Replace with your actual DAG ID

    - name: Shut down Airflow containers
      run: |
        docker-compose -f docker-compose.yml down