name: Trigger Model Development Pipeline DAG

on:
  push:
    branches:
      - 'vignesh_cicd_check'  # Replace with the actual branch name you want to monitor

jobs:
  trigger_dag:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Build and run Airflow with Docker
      run: |
        # Start the Docker containers for Airflow
        docker compose -f docker-compose.yaml up -d
        
        # Wait for Airflow web server to be ready
        until [ "$(docker compose exec bank_marketing_prediction_mlops-airflow-webserver-1 curl -s -o /dev/null -w '%{http_code}' http://localhost:8080)" == "200" ]; do
          echo "Waiting for Airflow webserver to be ready..."
          sleep 5
        done
        
        # Trigger the DAG locally
        docker compose exec bank_marketing_prediction_mlops-airflow-webserver-1 airflow dags trigger ModelDevelopmentPipeline  # Replace with your actual DAG ID

    - name: Shut down Airflow containers
      run: |
        docker compose -f docker-compose.yaml down