name: Trigger Airflow DAG

on:
  push:
    branches:
      - vignesh_model_dev_3  # Replace with your target branch

jobs:
  trigger-dag:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up Docker
      uses: docker/setup-buildx-action@v2
      
    - name: Run Airflow and trigger DAG
      run: |
        docker-compose up -d
        sleep 30  # Wait for Airflow to initialize
        docker exec airflow-webserver airflow dags trigger ModelDevelopmentPipeline
        docker-compose down