name: Trigger Airflow DAG

on:
  push:
    branches:
      - vignesh_model_dev_3  # Replace with your target branch

jobs:
  trigger-dag:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Install Docker Compose
      run: |
        sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2
      
    - name: Run Airflow and trigger DAG
      run: |
        docker compose up -d
        sleep 30  # Wait for Airflow to initialize
        docker exec bank_marketing_prediction_mlops-airflow-webserver-1 airflow dags trigger ModelDevelopmentPipeline

    - name: Wait for DAG completion and fetch logs
      run: |
        sleep 60  # Wait for DAG to start and run (adjust time as needed)
        
        # List DAG runs
        docker exec bank_marketing_prediction_mlops-airflow-webserver-1 airflow dags list-runs -d ModelDevelopmentPipeline
        
        # Get the latest DAG run ID
        DAG_RUN_ID=$(docker exec bank_marketing_prediction_mlops-airflow-webserver-1 airflow dags list-runs -d ModelDevelopmentPipeline | awk 'NR==4 {print $2}')
        
        # Fetch logs for each task in the DAG
        TASKS=$(docker exec bank_marketing_prediction_mlops-airflow-webserver-1 airflow tasks list ModelDevelopmentPipeline)
        for TASK in $TASKS
        do
          echo "Logs for task: $TASK"
          docker exec bank_marketing_prediction_mlops-airflow-webserver-1 airflow tasks logs -t ModelDevelopmentPipeline $TASK $DAG_RUN_ID
          echo "----------------------------------------"
        done
    - name: Shutdown Airflow
      run: docker compose down