name: Python Unittests

on:
  push:
    branches:
      - main
      - vignesh_ci_cd
      - tejesvani_test
      - hashwanth_model_changes
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'  # Update to Python 3.10

      - name: Remove 'os' from requirements.txt
        run: sed -i '/^os$/d' requirements.txt

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt || echo "Some packages failed to install, continuing with available packages"

      - name: Run unittests
        run: python -m unittest discover -v

      - name: Notify on success
        if: success()
        run: echo "Unit tests passed successfully"

      - name: Notify on failure
        if: failure()
        run: echo "Unit tests failed"