name: Python Unittests

on:
  push:
    branches:
      - main
      - vignesh_ci_cd
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run unittests
      run: python -m unittest discover -v

    - name: Notify on success
      if: success()
      run: echo "Unit tests passed successfully"

    - name: Notify on failure
      if: failure()
      run: echo "Unit tests failed"