name: CI/CD Pipeline for Model Development and Unittests

# Trigger the workflow on push or pull request to specific branches
on:
  push:
    branches:
      - main
      - vignesh_ci_cd
      - tejesvani_test
      - hashwanth_model_pipeline
  pull_request:
    branches:
      - main

jobs:
  # Job to set up the environment and run tests and model development
  build-and-develop:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the code from the repository
    - name: Checkout code
      uses: actions/checkout@v2

    # Step 2: Set up Python environment (Python 3.8)
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    # Step 3: Remove 'os' from requirements.txt (if present)
    - name: Remove 'os' from requirements.txt (if applicable)
      run: sed -i '/^os$/d' requirements.txt

    # Step 4: Install dependencies from requirements.txt
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt || echo "Some packages failed to install, continuing with available packages"

    # Step 5: Run unit tests using unittest discovery (if you have a 'tests' folder)
    - name: Run unit tests
      run: |
        python -m unittest discover tests

    # Step 6: Notify on success if all tests pass
    - name: Notify on success
      if: success()
      run: echo "Unit tests passed successfully"

    # Step 7: Notify on failure if any test fails
    - name: Notify on failure
      if: failure()
      run: echo "Unit tests failed"

    # Step 8: Run model development script using MLflow
    - name: Run Model Development with MLflow
      run: |
        python src/Model_Pipeline/model_development_with_mlflow.py
